version: '3.8'
services:
  app1:
    build: ./app1
    container_name: app
    ports:
      - "5000:5000"
    networks:
      - app-network

  app2:
    build: ./app2
    container_name: app
    ports:
      - "5001:5001"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
